name: build and push fsbback docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Conatainer
      working-directory: ./fsbback
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fsbback:latest . --no-cache
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fsbback:latest
