name: publish front

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev' 
    - name: build
      working-directory: ./fsbfront
      run: |
        flutter pub get
        flutter build web
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./fsbfront/build/web
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
