name: publish front

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev' 
      - name: build
        working-directory: ./fsbfront
        run: |
          flutter pub get
          flutter build web --web-renderer html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages
          folder: ./fsbfront/build/web
          
